name: >
  Publish 'Arcane Wizard: Library'
run-name: >
  Publish 'Arcane Wizard: Library' (${{ github.event.inputs.release-type }})

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Art des Releases'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Alpha
      release-tag:
        description: 'neuer Tag (manuell)'
        required: false
      build:
        description: 'Release erstellen'
        required: false
        default: true
        type: boolean
      full-changelog:
        description: 'vollständiges Changelog erstellen'
        required: false
        default: true
        type: boolean
  # schedule:
  #   # 16. Juni, 18:00 Europe/Berlin (16:00 UTC)
  #   - cron: "0 16 16 6 *"

permissions: {}

jobs:
  call-blueprint:
    uses: wow-addon-dev/.github/.github/workflows/release_blueprint.yml@main
    with:
      release-type: ${{ inputs.release-type || 'Release' }}
      release-tag: ${{ inputs.release-tag || '' }}
      build: ${{ github.event_name != 'workflow_dispatch' || inputs.build }}
      full-changelog: ${{ github.event_name != 'workflow_dispatch' || inputs.full-changelog }}
      cf-project-id: ${{ vars.CF_PROJECT_ID }}
    secrets: inherit
